$:
  vscode:
    - docker:
        image: cnbcool/default-dev-env:latest
      services:
        - name: vscode
          options:
            onlyPreview: true
            daemon: true
            launch: |
              cd /workspace/cyber-detective
              npm ci
              npm run build
              npx serve dist -l 8686 -s --no-clipboard
            keepAliveTimeout: 30m
